# Generated by Django 4.1.6 on 2023-07-10 07:04

import apps.organization.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='adele/Excel/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='adele/PDF/')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='Courier')),
                ('jshr', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='uz', max_length=100, null=True)),
                ('auto_type', models.CharField(choices=[('piyoda', 'Piyoda'), ('velosipet', 'Velosipet'), ('mashina', 'Mashina')], default='piyoda', max_length=100)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='Organization')),
                ('district', models.CharField(max_length=223, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('adeles', models.ManyToManyField(blank=True, related_name='organization', to='organization.adele')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=225, null=True)),
                ('logo', models.ImageField(upload_to='partners_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='UpLoadLetterExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='UpLoadLetterExcel', validators=[apps.organization.models.UpLoadLetterExcel.validate_even_number])),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='UpLoadLetterPDF', validators=[apps.organization.models.UpLoadLetterExcel.validate_even_number])),
                ('response', models.FileField(blank=True, null=True, upload_to='UpLoadLetterExcelResponse', validators=[apps.organization.models.UpLoadLetterExcel.validate_even_number])),
                ('status', models.CharField(choices=[('process', 'Process'), ('failed', 'Failed'), ('finished', 'Finished')], default='process', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadexcels', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UploadError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uploadexcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaderrors', to='organization.uploadletterexcel')),
            ],
        ),
        migrations.CreateModel(
            name='InComeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_letter', models.PositiveIntegerField(blank=True, null=True)),
                ('delivered', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('this_month', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='organization.organization')),
                ('upload_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomesorgannization', to='organization.uploadletterexcel')),
            ],
        ),
        migrations.CreateModel(
            name='InComeCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_letter', models.PositiveIntegerField(blank=True, null=True)),
                ('delivered', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('this_month', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='organization.courier')),
                ('upload_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomescourier', to='organization.uploadletterexcel')),
            ],
        ),
    ]
