# Generated by Django 4.2.5 on 2023-10-06 05:54

import apps.organization.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLetterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='UploadLetterPDFResponse', validators=[apps.organization.models.UploadLetterPDF.validate_even_number])),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='UploadLetterPDF', validators=[apps.organization.models.UploadLetterPDF.validate_even_number])),
                ('status', models.CharField(choices=[('process', 'Process'), ('failed', 'Failed'), ('finished', 'Finished')], default='process', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_zip_files', to='organization.organization')),
            ],
        ),
    ]
