# Generated by Django 4.1.6 on 2023-08-31 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('baseabstractdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.baseabstractdate')),
                ('letter_counter', models.BigIntegerField(blank=True, null=True)),
            ],
            bases=('account.baseabstractdate',),
        ),
        migrations.AddField(
            model_name='letter',
            name='personal_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
