# Generated by Django 4.2.5 on 2023-10-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_uploadletterpdf'),
        ('letter', '0002_counter_letter_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='upload_zip_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_letters', to='organization.uploadletterpdf'),
        ),
    ]
